
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxocydbkrusgbyvssbpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4b2N5ZGJrcnVzZ2J5dnNzYnBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MjE1NTMsImV4cCI6MjA1OTE5NzU1M30.mqZ0g_S1glDnnktxVOGJwUt5w_6zPwyAiaVUCB9_YR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
